### ISSUE TITLE
Stay at Fetching MX details

### ISSUE THREAD

**Issue by Thedarklife74** [benbenbenbenbenbenbenbenbenben/meraki-vpn-map#1]
Configuration are complete but stay at Fetching Mx details from server

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
I have added some new code to the dashboard.js file. It will now log the HTTP status codes for each call. Redeploy and monitor the server console for which API call is failing.

**Comment by Spangsberg** [comment]
> I have added some new code to the dashboard.js file. It will now log the HTTP status codes for each call. Redeploy and monitor the server console for which API call is failing.

Hi Ben

Thank you for this utility, it looks really promising.

I was seconds away from posting that I had the same Fetching issue, but I have just deployed the updated script, and now the errors are put to the server console:

Server running on port 3000
running getAll function
get https://api.meraki.com/api/v0/organizations/XXXX/vpnFirewallRules
get https://api.meraki.com/api/v0/organizations/XXXX/deviceStatuses
 get https://api.meraki.com/api/v0/networks/XXXX/devices/Q3AA-FPMH-XXXX 429 Too Many Requests
 get https://api.meraki.com/api/v0/networks/XXXX/devices/Q3AA-NAFP-XXXX 429 Too Many Requests
 get https://api.meraki.com/api/v0/networks/XXXX/devices/Q3AA-SK8G-XXXX 429 Too Many Requests
 get https://api.meraki.com/api/v0/networks/XXXX/devices/Q3AA-GCHZ-XXXX429 Too Many Requests
get https://api.meraki.com/api/v0/networks/XXXX/devices/Q3AA-G24D-XXXX
get https://api.meraki.com/api/v0/networks/XXXX/devices/Q3AA-H7DU-XXXX
get https://api.meraki.com/api/v0/networks/XXXX/devices/Q3AA-NESN-XXXX
 get https://api.meraki.com/api/v0/networks/XXXX/devices/Q3AA-RRYS-XXXX 429 Too Many Requests
get https://api.meraki.com/api/v0/networks/XXXX/devices/Q3AA-F4RS-XXXX

(The first two requests are successful, after that, everything is red)

It appears the API rate limit (5 requests/sec)is being breached. In this dashboard I have around 60 MX networks and 4-500 devices.




EDIT:

In app.js I changed the minTime to 400, and in dashboard.js I changed the base URL from api.meraki.com to the actual server hosting my dashboard (m213.meraki.com in my case)

This seems to have eliminated the rate limit problem, but a new issue has popped up.

The MX84 and MX250 doesn't support the /Performance parameter, which is now a show stopper....

Server console output:
 get https://n213.meraki.com/api/v0/networks/XXXXX/devices/Q2PN-NKNM-XXXX/performance 400 Bad Request

Result from same request performed in Postman:
{
    "errors": [
        "Feature not supported"
    ]
}

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
Cheers for the update, the only thing I could think was if other API calls are running it would hit the rate limit as bottleneck should stop that. Glad it works with increased time. Let me check that perf call

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
Is the MX84/250 performance call going to the warm spare?

**Comment by Spangsberg** [comment]
> Is the MX84/250 performance call going to the warm spare?

Good call, I confirm these errors are from the standby HA device.

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
> Good call, I confirm these errors are from the standby HA device.
Thanks for confirming, that makes sense, the code just picks the first MX of HA pair. I will make some code changes to select the active MX!

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
Thanks for confirming, that makes sense, the code just picks the first MX of HA pair. I will make some code changes to select the active MX!

**Comment by Thedarklife74** [comment]
Hi i still have some problem. Server is now loading all devices but after some "get" the terminal say : "429 Too many requests and all text become RED.

Also the the Map it always say FOr developpement purpose only but i have all google maps API active on my key

**Comment by Spangsberg** [comment]
> Hi i still have some problem. Server is now loading all devices but after some "get" the terminal say : "429 Too many requests and all text become RED.
> 
> Also the the Map it always say FOr developpement purpose only but i have all google maps API active on my key

Hi

Same issue I saw initially, but if you do a couple of file updates, like I described above, you should be able to eliminate the 429 error (Rate limit)

**Comment by Thedarklife74** [comment]
> > Hi i still have some problem. Server is now loading all devices but after some "get" the terminal say : "429 Too many requests and all text become RED.
> > Also the the Map it always say FOr developpement purpose only but i have all google maps API active on my key
> 
> Hi
> 
> Same issue I saw initially, but if you do a couple of file updates, like I described above, you should be able to eliminate the 429 error (Rate limit)

Ok done. No more this problem but now it seems the GetAll function restart again and again

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
> > > Hi i still have some problem. Server is now loading all devices but after some "get" the terminal say : "429 Too many requests and all text become RED.
> > > Also the the Map it always say FOr developpement purpose only but i have all google maps API active on my key
> > 
> > 
> > Hi
> > Same issue I saw initially, but if you do a couple of file updates, like I described above, you should be able to eliminate the 429 error (Rate limit)
> 
> Ok done. No more this problem but now it seems the GetAll function restart again and again

It should only run once per page load. What are the last lines before it runs the main function again?

**Comment by Thedarklife74** [comment]
> > > > Hi i still have some problem. Server is now loading all devices but after some "get" the terminal say : "429 Too many requests and all text become RED.
> > > > Also the the Map it always say FOr developpement purpose only but i have all google maps API active on my key
> > > 
> > > 
> > > Hi
> > > Same issue I saw initially, but if you do a couple of file updates, like I described above, you should be able to eliminate the 429 error (Rate limit)
> > 
> > 
> > Ok done. No more this problem but now it seems the GetAll function restart again and again
> 
> It should only run once per page load. What are the last lines before it runs the main function again?

I load the page only one Time and the GetAll function run maybe 6 or 7 time before I stop It manually

**Comment by Spangsberg** [comment]
> > > > > Hi i still have some problem. Server is now loading all devices but after some "get" the terminal say : "429 Too many requests and all text become RED.
> > > > > Also the the Map it always say FOr developpement purpose only but i have all google maps API active on my key
> > > > 
> > > > 
> > > > Hi
> > > > Same issue I saw initially, but if you do a couple of file updates, like I described above, you should be able to eliminate the 429 error (Rate limit)
> > > 
> > > 
> > > Ok done. No more this problem but now it seems the GetAll function restart again and again
> > 
> > 
> > It should only run once per page load. What are the last lines before it runs the main function again?
> 
> I load the page only one Time and the GetAll function run maybe 6 or 7 time before I stop It manually

I also see the GetAll function console notice several time during data loading. I haven't looked closer into whether the function starts all over, or just continues and queues additional requests.
Could I the some kind of auto update from the browser, while waiting for the initial data load?

get https://n213.meraki.com/api/v0/networks/XXXXXX/devices/Q2KW-U4K8-XXXX
get https://n213.meraki.com/api/v0/networks/XXXXXX/devices/Q2KW-5DMY-XXXX
get https://n213.meraki.com/api/v0/networks/XXXXXX/devices/Q2KW-3NNR-XXXX
running getAll function
get https://n213.meraki.com/api/v0/networks/XXXXXX/devices/Q2KW-9N67-XXXX
get https://n213.meraki.com/api/v0/networks/XXXXXX/devices/Q2KW-5BPL-XXXX
get https://n213.meraki.com/api/v0/networks/XXXXXX/devices/Q2KW-XX8B-XXXX
get https://n213.meraki.com/api/v0/networks/XXXXXX/devices/Q2KW-XSVX-XXXX
get https://n213.meraki.com/api/v0/networks/XXXXXX/devices/Q2KW-DFDT-XXXX

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
Thanks for the feedback guys. I have resolved the warm spare issue, it will now select the primary MX.
I've not been able to reproduce the getall function being repeated yet. How many api calls are happening from the first and the last getall function message? 

On the browser developer tab is it fetching mxs multiple times?
<img width="760" alt="screenshot-developer" src="https://user-images.githubusercontent.com/52065202/69664884-240ed980-1081-11ea-9b98-36773497c19a.png">

**Comment by Spangsberg** [comment]
> Thanks for the feedback guys. I have resolved the warm spare issue, it will now select the primary MX.
> I've not been able to reproduce the getall function being repeated yet. How many api calls are happening from the first and the last getall function message?
> 
> On the browser developer tab is it fetching mxs multiple times?
> <img alt="screenshot-developer" width="760" src="https://user-images.githubusercontent.com/52065202/69664884-240ed980-1081-11ea-9b98-36773497c19a.png">

HI Ben

Thank you for your patience and efforts.

I just did a count, and the Getall function reappeared after approximately 260 devices.

I will update the scripts, and report back on the spare MX issue.

**Comment by Spangsberg** [comment]
Updates applied and process restartet.

now the Getall process runs all the way, and end up with a Finished Successfully (took 7 minutes), but the webpage never changes status from Fetching MX details.....

**Comment by Thedarklife74** [comment]
> Updates applied and process restartet.
> 
> now the Getall process runs all the way, and end up with a Finished Successfully (took 7 minutes), but the webpage never changes status from Fetching MX details.....

Exactly the same problem for me

**Comment by Spangsberg** [comment]
This morning I tried connecting to a dashboard with only 2 MX devices, and everything seems to be working fine, so I guess the massive amount of data from 60 MX appliances brings the script to it's knees....

**Comment by Thedarklife74** [comment]
> This morning I tried connecting to a dashboard with only 2 MX devices, and everything seems to be working fine, so I guess the massive amount of data from 60 MX appliances brings the script to it's knees....

Personnaly I have more than 1000 devices on my dashboard and the script do the GetAll function on all devices. It could be better to execute the GetAll only On Appliances. And not on Access Point

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
Thanks for the feedback guys. Several fixes in Dev branch:
Increased server timeout from 2 to 10 minutes,
Reworked API calls for more efficiency,
Server stores results of API to make client-side faster,
Credentials store in config file (update and change to config.js)
This should hopefully resolve the issues you were facing, let me know if more issues arrise.

**Comment by Spangsberg** [comment]
> Thanks for the feedback guys. Several fixes in Dev branch:
> Increased server timeout from 2 to 10 minutes,
> Reworked API calls for more efficiency,
> Server stores results of API to make client-side faster,
> Credentials store in config file (update and change to config.js)
> This should hopefully resolve the issues you were facing, let me know if more issues arrise.

Hi Ben

Again, thank you for your efforts. I have a couple of busy days ahead, but as soon as I have a few spare minutes, I will apply the updates and report back.

**Comment by Spangsberg** [comment]
Downloaded the new branch, now I get this:

dnie@dkhqlog02:~/meraki-vpn-map$ node src/app.js
module.js:550
    throw err;
    ^

Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/dnie/meraki-vpn-map/src/app.js:7:17)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
dnie@dkhqlog02:~/meraki-vpn-map$

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
You may need to run **npm install** again as its a new branch

**Comment by Spangsberg** [comment]
Got the new code branch running, and it worked well with my small 2-device dashboard.
Getall process also runs successfully on the large dashboard (6 minutes), but the web page stays in the Fetching MX Details... view forever. 
During the GetAll process, I did notice that it seems to start over, in the middle of the run, and it also reports Completed sucessfully, and the continues the query. (See attached sceenshots)

I have no clue on JS programming, so I don't know the effort included in the next question, but would it be possible to filter the devices, and only poll details for MX devices, and not MS, MR and MV?

![Capture](https://user-images.githubusercontent.com/58219639/70120798-a42ed380-166d-11ea-835c-2ca95827853e.PNG)
![Capture2](https://user-images.githubusercontent.com/58219639/70120800-a42ed380-166d-11ea-8db3-d8273af9eab8.PNG)

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
Thanks for the feedback, the server timeout was incorrectly set to 1 minute instead of 10 minutes that's why seeing the loop. 

Looks like you may be running the old code, the new dev branch no longer logs running getAll function, plus has some additional startup logging. This may be why you are still seeing the get requests for non-MX related devices. Dev branch will only fetch MX's. 

Server start should look like:

```
VPN App listening on port 3000!
===============================
Checking ongoing APIs
get https://api.meraki.com/api/v0/organizations/xxxxxx/apiRequests
Average API Calls over last  60  seconds =  6 %
Recommended Bottleneck setting =  200
=======================================
Running main function
get https://api.meraki.com/api/v0/organizations/xxxxx/deviceStatuses
=======================================
Executing Approx. 24 calls  - Estimated Time: 4.9 s
=======================================
```

**Comment by Spangsberg** [comment]
Hi Ben

Thank you for your patience, I am on a steep learning curve here, this is the first time I pull an "unfinished" application from Github, so cloning the right branch took another Google request ;-)

NOW I have the new branch, and it is a huge improvement, polling my large dashboard now takes roughly 280 seconds, and the result is drawn on the web interface, just like is should, but zooming in too closes, losses the overlay on the Google map....

I also see I have a couple of feature request ;-) 
Would it be possible to include VPN Enabled static routes in the VPN check? 
Would it be possible to test specific TCP/UDP destination ports against the firewall rules? 


![Capture](https://user-images.githubusercontent.com/58219639/70126995-79974780-167a-11ea-9a74-f2d081387961.PNG)
![Capture2](https://user-images.githubusercontent.com/58219639/70126996-79974780-167a-11ea-881e-ea1b9d2ab89c.PNG)

**Comment by Thedarklife74** [comment]
I've download the dev branch a do a complete isntall and I've got this message 


module.js:549
    throw err;
    ^

Error: Cannot find module './config'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/damien/meraki-vpn-map-dev/src/app.js:2:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
> I've download the dev branch a do a complete isntall and I've got this message
> 
> module.js:549
> throw err;
> ^
> 
> Error: Cannot find module './config'
> at Function.Module._resolveFilename (module.js:547:15)
> at Function.Module._load (module.js:474:25)
> at Module.require (module.js:596:17)
> at require (internal/module.js:11:18)
> at Object. (/home/damien/meraki-vpn-map-dev/src/app.js:2:16)
> at Module._compile (module.js:652:30)
> at Object.Module._extensions..js (module.js:663:10)
> at Module.load (module.js:565:32)
> at tryModuleLoad (module.js:505:12)
> at Function.Module._load (module.js:497:3)

Just rename the config-default.js file to config.js

**Comment by benbenbenbenbenbenbenbenbenben** [comment]
> Hi Ben
> 
> Thank you for your patience, I am on a steep learning curve here, this is the first time I pull an "unfinished" application from Github, so cloning the right branch took another Google request ;-)
> 
> NOW I have the new branch, and it is a huge improvement, polling my large dashboard now takes roughly 280 seconds, and the result is drawn on the web interface, just like is should, but zooming in too closes, losses the overlay on the Google map....
> 
> I also see I have a couple of feature request ;-)
> Would it be possible to include VPN Enabled static routes in the VPN check?
> Would it be possible to test specific TCP/UDP destination ports against the firewall rules?
> 

Thanks for your feedback :). I have created new thread for the zoom issue. This may take some digging. 
Also have a new thread for feature requests!

**Comment by Thedarklife74** [comment]
Seems to be ok now it work well :) Nice projet hope new feature !
